# Generated by Django 3.1.3 on 2020-12-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201216_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Ссылка(для видео)'),
        ),
    ]
