# Generated by Django 3.1.3 on 2020-12-30 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201221_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rubric',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='main.rubric', verbose_name='Рубрика'),
        ),
    ]
